### PR TITLE
Add support for provider_specific attributes on wls_authentication_provider

### PR DESCRIPTION
**Pull request by hajee**
This PR provides the `provider_specific`  propery on `wls_authentication_provider`. Using this property, you can manage the attributes from any type of authentication_provider. This PR also add's deprecation messages to `attributes` and `attributesvalues`.

### CODE REVIEW

**Comment by biemond** [comment]
He Bert, 

it's still got some bugs

The create goes well but the second time it hangs on the fetch (2nd time). It looks like you only tested with 1 attribute or never run it twice.

this in the fetch of WLST is not valid 
    attribute_names = PrincipalCacheTTLSSLEnabledCacheSizePortHostMaxGroupMembershipSearchLevel

I change the fetch and removed the attributes

But got a bug with SSLEnabled it won't set it to enable , tried 1 and '1' but had to use 'true' but when I retrieve it I will get 0 or 1 and not true or false.

So do you handle all int, string or boolean situations like I did before because it is now not backwards compatible and will lead to changes everytime you run puppet.

the old config did this,

          numbers  = ['Port','CacheTTL','CacheSize','MaxGroupMembershipSearchLevel']
          booleans = ['KeepAliveEnabled','UseRetrievedUserNameAsPrincipal','IgnoreDuplicateMembership','DigestReplayDetectionEnabled','UseDefaultUserNameMapper','SSLEnabled']
          lists =    ['ActiveTypes']

          i = 0
          for property in properties:

            print "set property " + property + " value "+ values[i]
            if property in numbers:
              print "is a int"
              set(property,int(values[i]))

            elif property in booleans:
              print "is a boolean"
              if values[i] == '1' or values[i] == 1:
                print "True"
                try:
                  set(property,true)
                except:
                  print "failed to set boolean true, trying string"
                  try:
                    set(property, 'true')
                  except:
                    raise
              else:
                try:
                  set(property,false)
                except:
                  print "failed to set boolean false, trying string"
                  try:
                    set(property, 'false')
                  except:
                    raise

            elif property in lists:
              print "is a list"

              list_values=String(values[i]).split("::")
              set(property,jarray.array(list_values, String))

            else:
              print "is a string"
              set(property,values[i])

            i = i + 1


tested configuration

      'ldap':
        ensure:             'present'
        control_flag:       'SUFFICIENT'
        providerclassname:  'weblogic.security.providers.authentication.LDAPAuthenticator'
        provider_specific:
           'Principal':                     'ldapuser'
           'Host':                          'ldapserver'
           'Port':                          '389'
           'CacheTTL':                      '60'
           'CacheSize':                     '1024'
           'MaxGroupMembershipSearchLevel': '4'
           'SSLEnabled':                    '1'
        order:              '1'

this is the change to fetch

So I removed the attributes and used provider keys

    real_domain='<%= current_resource.domain %>'

    def quote(text):
        if text or text == '':
            return "\"" + str(text).replace("\"", "\"\"") + "\""
        else:
            return ""

    name            = '<%= current_resource.authentication_provider_name %>'
    realmName       = cmo.getSecurityConfiguration().getDefaultRealm()
    cd('/')
    path            = getPath(realmName)
    cd(path + '/AuthenticationProviders/' + name)

    try:
      puppet = open("/tmp/wlstScript.out", "w")
      print >>puppet, ';'.join('<%= current_resource.provider_specific.keys.join(',') -%>'.split(","))
      #
      # Get all specified values
      #
    <% current_resource.provider_specific.keys.each do | key | -%>
      <%= key -%> = str(get('<%= key -%>'))
      print '<%= key -%> is ' + <%= key %>
    <% end -%>
      #
      # All values fetched
      #
      print >>puppet, ';'.join(map(quote,[<%= current_resource.provider_specific.keys.join(',') -%>]))
      puppet.close()
      print "~~~~COMMAND SUCCESFULL~~~~"


    except:
      print "Unexpected error:", sys.exc_info()[0]
      print "~~~~COMMAND FAILED~~~~"
      raise

**Comment by hajee** [comment]
Edwin,

I'll look into it on monday. Is that ok?

**Comment by biemond** [comment]
perfect, 

the master is with the fetch fix ok again.

**Comment by biemond** [comment]
Plus some attributes you can set but not retrieve with fetch 

   'ActiveDirectoryAuthenticator':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
    providerclassname:  'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator'
    provider_specific:
      'Credential':                     'password'
      'GroupBaseDN':                    'DC=ad,DC=company,DC=org'
      'GroupFromNameFilter':            '(&(sAMAccountName=%g)(objectclass=group))'
      'GroupMembershipSearching':       'limited'
      'Host':                           'ad.company.org'
      'MaxGroupMembershipSearchLevel':  0
      'Principal':                      'CN=SER_WASadmin,OU=Service Accounts,DC=ad,DC=company,DC=org'
      'UserBaseDN':                     'DC=ad,DC=company,DC=org'
      'UserFromNameFilter':             '(&(sAMAccountName=%u)(objectclass=user))'
      'UserNameAttribute':              'sAMAccountName'
      'Port':                           389
    order:              '2'
   


    ==> admin: Info: Executing: wlstScript with action execute
    ==> admin: Prepare to run: /tmp/wlstScript20151231-23447-1pek0rd-0.py,wls,default,/opt/oracle/middleware11g/wlserver_10.3,weblogic,weblogic1,t3://10.10.10.10:7001
    ==> admin: vvv===================================================================
    ==> admin: real_domain='default'
    ==> admin: def quote(text):
    ==> admin:     if text or text == '':
    ==> admin:         return "\"" + str(text).replace("\"", "\"\"") + "\""
    ==> admin:     else:
    ==> admin:         return ""
    ==> admin: name            = 'ActiveDirectoryAuthenticator'
    ==> admin: realmName       = cmo.getSecurityConfiguration().getDefaultRealm()
    ==> admin: cd('/')
    ==> admin: path            = getPath(realmName)
    ==> admin: cd(path + '/AuthenticationProviders/' + name)
    ==> admin:
    ==> admin: try:
    ==> admin:   puppet = open("/tmp/wlstScript.out", "w")
    ==> admin:   print >>puppet, ';'.join('Host,UserNameAttribute,Credential,UserFromNameFilter,GroupMembershipSearching,Port,UserBaseDN,MaxGroupMembershipSearchLevel,GroupBaseDN,Principal,GroupFromNameFilter'.split(","))
    ==> admin:   #
    ==> admin:   # Get all specified values
    ==> admin:   #
    ==> admin:   Host = str(get('Host'))
    ==> admin:   print 'Host is ' + Host
    ==> admin:   UserNameAttribute = str(get('UserNameAttribute'))
    ==> admin:   print 'UserNameAttribute is ' + UserNameAttribute
    ==> admin:   Credential = str(get('Credential'))
    ==> admin:   print 'Credential is ' + Credential
    ==> admin:   UserFromNameFilter = str(get('UserFromNameFilter'))
    ==> admin:   print 'UserFromNameFilter is ' + UserFromNameFilter
    ==> admin:   GroupMembershipSearching = str(get('GroupMembershipSearching'))
    ==> admin:   print 'GroupMembershipSearching is ' + GroupMembershipSearching
    ==> admin:   Port = str(get('Port'))
    ==> admin:   print 'Port is ' + Port
    ==> admin:   UserBaseDN = str(get('UserBaseDN'))
    ==> admin:   print 'UserBaseDN is ' + UserBaseDN
    ==> admin:   MaxGroupMembershipSearchLevel = str(get('MaxGroupMembershipSearchLevel'))
    ==> admin:   print 'MaxGroupMembershipSearchLevel is ' + MaxGroupMembershipSearchLevel
    ==> admin:   GroupBaseDN = str(get('GroupBaseDN'))
    ==> admin:   print 'GroupBaseDN is ' + GroupBaseDN
    ==> admin:   Principal = str(get('Principal'))
    ==> admin:   print 'Principal is ' + Principal
    ==> admin:   GroupFromNameFilter = str(get('GroupFromNameFilter'))
    ==> admin:   print 'GroupFromNameFilter is ' + GroupFromNameFilter
    ==> admin:   #
    ==> admin:   # All values fetched
    ==> admin:   #
    ==> admin:   print >>puppet, ';'.join(map(quote,[Host,UserNameAttribute,Credential,UserFromNameFilter,GroupMembershipSearching,Port,UserBaseDN,MaxGroupMembershipSearchLevel,GroupBaseDN,Principal,GroupFromNameFilter]))
    ==> admin:   puppet.close()
    ==> admin:   print "~~~~COMMAND SUCCESFULL~~~~"
    ==> admin:
    ==> admin:
    ==> admin: except:
    ==> admin:   print "Unexpected error:", sys.exc_info()[0]
    ==> admin:   print "~~~~COMMAND FAILED~~~~"
    ==> admin:   raise
    ==> admin: ^^^====================================================================
    ==> admin: Info: Executing wls-script /tmp/wlstScript20151231-23447-1pek0rd-0.py with timeout = 120
    ==> admin: Debug: Passing domain default
    ==> admin: Debug: Passing credentials to WLST
    ==> admin: Info: Connecting to wls on url t3://10.10.10.10:7001
    ==> admin: Debug: wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> Connecting to t3://10.10.10.10:7001 with userid weblogic ...
    ==> admin:
    ==> admin: Debug: Successfully connected to Admin Server 'AdminServer' that belongs to domain 'Wls1036'.
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: Warning: An insecure protocol was used to connect to the
    ==> admin:
    ==> admin: Debug: server. To ensure on-the-wire security, the SSL port or
    ==> admin:
    ==> admin: Debug: Admin port should be used instead.
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: wls:/Wls1036/serverConfig> Host is ad.company.org
    ==> admin:
    ==> admin: Debug: UserNameAttribute is sAMAccountName
    ==> admin:
    ==> admin: Debug: This Exception occurred at Thu Dec 31 14:14:30 CET 2015.
    ==> admin:
    ==> admin: Debug: weblogic.management.NoAccessRuntimeException: Access to sensitive attribute in clear text is not allowed due to the setting of ClearTextCredentialAccessEnabled attribute in SecurityConfigurationMBean. Attr: Credential, MBean name: Security:Name=myrealmActiveDirectoryAuthenticator
    ==> admin:
    ==> admin: Debug: Unexpected error: main.WLSTException
    ==> admin:

**Pull request merged**
