### PR TITLE
[wls_datasource] Added password property. Closes #283

### LINKED ISSUE #283: wls_datasource modify.py.erb doesn't change password
files/providers/wls_datasource/modify.py.erb doesn't currently have the ability to change/set the password on the datasource.

### PR DESCRIPTION
**Pull request by hajee**
In this PR adds support for setting encrypted and non encrypted passwords for datasources

There are two ways you can use this property:

1. with an encrypted value
2. with a clear text password

Usage with a encrypted password:

```puppet
    wls_datasource { ....:
      ...
      password => '{AES}yAf7w4hKUOa3XSUsPCPb1LWnwy0PSNiq7+HAahXXWQY=',
      ...
    }
```
Puppet treats everything that starts with `{...}`, where the dots are uppercase letters,
as an encrypted value. These values are passed directly to WebLogic and stored in the domain.

A method to get the encrypted value would be:

1. Set the password through the WebLogic management interface
2. User `puppet resource wls_datasource datsource_name` to get all information including the 
   encrypted password.

Usage with a clear text password:

```puppet
    wls_datasource { ....:
      ...
      password => 'clear_text_password',
      ...
    }
```
Clear text passwords are passed to WebLogic for encryption and then stored in the database.

To get this working I added:
1. Support for common methods over all actions.
2. some abstractions to make it easy to call wlst functiuons in ruby. 

These two elements can help us refacter some of the code, and implement other encrypted items.

### CODE REVIEW

**Comment by biemond** [comment]
Wow, very impressive.

Is encrypted password alg. your own hash? 
if it is the weblogic hash you cannot know it before you create it. Or you have to do this yourself in wlst, logon to the domain, encrypt, grep this output and use this in the create action. 
Every wlst domain has it own salt so you cannot use the encrypted password on other domains ( not like unix passwords)  and besides this if you want to use encrypted password this probably this is a task of puppet & hiera and not ours. So probably encrypted password shouldn't  be supported. 
when it is your own implementation then you also need to decrypt this one, the weblogic one and compare these, So your decrypt would be that difficult to use it so it is probably insecure. 

small change, I would do is a fixed function name in wls_decrypt_value.py.erb because you call this with wlst template("puppet:///modules/orawls/functions/#{function_name}.py.erb", caller_binding), this function must be same as the file name else you cannot call it.

**Comment by hajee** [comment]
>Is encrypted password alg. your own hash? 
if it is the weblogic hash you cannot know it before you create it. Or you have to do this yourself in wlst, logon to the domain, encrypt, grep this output and use this in the create action. 

You cannot know this up front. This is useful when you have set the password with the web interface and extract it with `puppet resource wls_datasource`

>Every wlst domain has it own salt so you cannot use the encrypted password on other domains ( not like unix passwords) and besides this if you want to use encrypted password this probably this is a task of puppet & hiera and not ours. So probably encrypted password shouldn't be supported. 
when it is your own implementation then you also need to decrypt this one, the weblogic one and compare these, So your decrypt would be that difficult to use it so it is probably insecure.

I used the example code from @Raskil. So no own encryption, just weblogic stuff. All the encryption code is called in the context of a domain, so it used the salt that is stored in the domain.

>small change, I would do is a fixed function name in wls_decrypt_value.py.erb because you call this with wlst template("puppet:///modules/orawls/functions/#{function_name}.py.erb", caller_binding), this function must be same as the file name else you cannot call it.

I used this construct, so we expand on the number of functions to call directly from ruby. For the `wls_authentication_provider`  I intend to add a couple of functions. So that is why the name is variable.

**Comment by Raskil** [comment]
Hi Bert,

´´´´python
def encrypted_password?
   !should.scan(/\A\{[A-Z]{3}\}.*\Z/).empty?
end
´´´´

should not work on old domains, because they use 3DES. Maybe better change the regex to !should.scan(/\A\{[0-9A-Z]{3}\}.*\Z/).empty? ?

**Comment by hajee** [comment]
@Raskil Thanks. If the string is `{3DES}` then maybe even remove the 3 from the regexp and turn it into:

```ruby
def encrypted_password?
   !should.scan(\A\{[0-9A-Z]*\}.*\Z/).empty?
end```

**Comment by Raskil** [comment]
@hajee yes, sounds good.

I'm scimming through your comparison algorithm and I fear they might not work as you expect them to. 
Your commit states:
"If the specified password is a plain text password, we ask WLS to decrypt is for us before comparing it to the specified value."
I assume you mean encrypt, not decrypt. But nevertheless, the used encryption algirithm uses some sort of initializationvector that is stored in the encrypted password.
What this means is the following: you can encrypt the same password multiple times and you will always get a different dncrypted string. So there is no sense in comparing encrypted password values, because it just won't tell you if the passwords are the same.

**Comment by hajee** [comment]
>I'm scimming through your comparison algorithm and I fear they might not work as you expect them to. 
Your commit states:
"If the specified password is a plain text password, we ask WLS to decrypt is for us before comparing it to the specified value."
I assume you mean encrypt, not decrypt. 

Yes you are right.

>But nevertheless, the used encryption algirithm uses some sort of initializationvector that is stored in the encrypted password.
What this means is the following: you can encrypt the same password multiple times and you will always get a different dncrypted string. So there is no sense in comparing encrypted password values, because it just won't tell you if the passwords are the same.

Like I said to @biemond, I use your example code. So that code decrypts the stored password and compare's the unencrypted password to the plain password given in the manifest. If they are the same, Puppet doesn't do anything. If they are noit the same, I use WLS to set the password en create the encrypted value.

**Comment by Raskil** [comment]
Ah ok, then maybe rework the documentation:

+    # If the specified password in the manifest is encrypted, we compare it
+    # with the fetched password (which is also encrypted). If the specified password 
+    # is a plain text password, we ask WLS to decrypt is for us before comparing it to the
+    # specified value.

Because it reads as if you are always comparing encrypted values :)

**Comment by hajee** [comment]
Actualy the documentation was right, but maybe needs some extra fluff ;-):

> If the specified password is a plain text password, we ask WLS to decrypt it for us before comparing it to the specified value.

If the password in the puppet manifest is a plan text password, Puppet asks Weblogic to decrypt the current datasource password stored in the domain and return this to puppet for comparisson. The Puppet code does not store the password on disk.

**Comment by Raskil** [comment]
Ah ok, now I get it.

**Comment by biemond** [comment]
Ok, let's make this encrypted a hidden feature and I will only support plain text as password. People should use encrypted hiera and I don't want to know & support all those situations & wls versions.

      I used this construct, so we expand on the number of functions to call directly from ruby. For the wls_authentication_provider I intend to add a couple of functions. So that is why the name is variable.

I mean line 8 of files/functions/wls_decrypt_value.py.erb. function must be the same as the file name else you cannot call it  from line 23 in lib/utils/wls_functions.rb. But this is a very minor issue.

**Pull request merged**
