### PR TITLE
Fix wls authentication provider

### PR DESCRIPTION
**Pull request by hajee**
It now correctly handles all types including encrypted values

### CODE REVIEW

**Comment by biemond** [comment]
We need to add documentation how wlst inside orawls works.

probably all those wlst helpers are they temporary or will they be skipped when they are still the same.
And some files like common.py don't have to be a template, we can use puppet file which will do a crc check.

**Comment by hajee** [comment]
Agree. 

For the future I was thinkin about an other abstraction from the ruby side than we have now. One that supports setting en fetch attributes via different implementations. The implementations can be wlst and the wls 12 rest interface. The business logic could then all be put in ruby/puppet code and using the new abstraction.

**Comment by biemond** [comment]
indeed,

but now I can already cleanup some wlst provider code  :+1:  , less code and more re-use

**Comment by hajee** [comment]
Yep. Maybe you can also use the `auto_typed_set` in more places. I think this will give you a major cleanup.

**Comment by biemond** [comment]
So booleans don't work, I keep on getting a javax.management.InvalidAttributeValueException on SSLEnabled with wls 10.3.6 . I tried 1, True and true

==> admin: Debug: Name : SSLEnabled
==> admin:
==> admin: Debug: Setting boolean property SSLEnabled to true
==> admin:
==> admin: Debug: This Exception occurred at Sun Jan 10 15:34:29 CET 2016.
==> admin:
==> admin: Debug: javax.management.InvalidAttributeValueException: argument type mismatch
==> admin:
==> admin: Debug: Unexpected error: main.WLSTException
==> admin:

    'ldap':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
    providerclassname:  'weblogic.security.providers.authentication.LDAPAuthenticator'
    provider_specific:
       'Principal':                     'ldapuser'
       'Host':                          'ldapserver'
       'Port':                          389
       'CacheTTL':                      60
       'CacheSize':                     1024
       'MaxGroupMembershipSearchLevel': 4
       'SSLEnabled':                    'true'

Now I will test credentials

**Comment by hajee** [comment]
You must use 0 and 1.

**Comment by biemond** [comment]
I tried everything, did you test it on wls 10.3?

**Comment by hajee** [comment]
No. Do you have a debug log for 10.3?

**Comment by biemond** [comment]
Also encrypted doesn't work on the index, It is there but I think we need to retrieve the CredentialEncypted , Credential is not allowed when it exists



==> admin: Info: Connecting to wls on url t3://10.10.10.10:7001
==> admin: Error: Could not prefetch wls_authentication_provider provider 'prefetching': Error fetching value for property: 'Credential' while in Wls_authentication_provider[ActiveDirectoryAuthenticator](provider=prefetching). Probably an unknown  propery.
==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/puppet/provider/wls_authentication_provider/prefetching.rb:42:in `prefetch'


wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm/AuthenticationProviders/ActiveDirectoryAuthenticator> ls()
dr--   Realm

-r--   AllGroupsFilter                              null
-r--   AllUsersFilter                               null
-r--   BindAnonymouslyOnReferrals                   false
-r--   CacheEnabled                                 true
-r--   CacheSize                                    32
-r--   CacheTTL                                     60
-r--   ConnectTimeout                               0
-r--   ConnectionPoolSize                           6
-r--   ConnectionRetryLimit                         1
-r--   ControlFlag                                  SUFFICIENT
-r--   Credential                                   ******
-r--   CredentialEncrypted                          ******

**Comment by hajee** [comment]
All on 10.3?

**Comment by hajee** [comment]
Tomorrow I'll provision a 10.3 host and look into it. I'm guessing the formatting of the wlst man pages is different, causing it to not see the data type and if the property is encrypted or not.

**Comment by biemond** [comment]
yep

    ==> admin: Info: create default/ldap
    ==> admin: Info: Executing: wlstScript with action
    ==> admin: Info: Got the right domain default script, now execute WLST
    ==> admin: Prepare to run: /tmp/wlstScript20160110-5569-148x5z9-0.py,wls,default,/opt/oracle/middleware11g/wlserver_10.3,weblogic,weblogic1,t3://10.10.10.10:7001
    ==> admin: vvv===================================================================
    ==> admin: # check the domain else we need to skip this (done in wls_access.rb)
    ==> admin: real_domain='default'
    ==> admin: name                      = 'ldap'
    ==> admin: control_flag              = 'SUFFICIENT'
    ==> admin: providerclassname         = 'weblogic.security.providers.authentication.LDAPAuthenticator'
    ==> admin: attributes                = ''
    ==> admin: attributesvalues          = ''
    ==> admin: order                     = ''
    ==> admin:
    ==> admin: edit()
    ==> admin: startEdit()
    ==> admin:
    ==> admin: try:
    ==> admin:
    ==> admin:     cd('/')
    ==> admin:     realmName  = cmo.getSecurityConfiguration().getDefaultRealm()
    ==> admin:     path = getPath(realmName)
    ==> admin:     cd(path)
    ==> admin:
    ==> admin:     cmo.createAuthenticationProvider(name, providerclassname)
    ==> admin:
    ==> admin:     cd('AuthenticationProviders/'+name)
    ==> admin:     #
    ==> admin:     # Set resource specific values
    ==> admin:     #
    ==> admin:     auto_typed_set('CacheSize', '1024')
    ==> admin:     auto_typed_set('Principal', 'ldapuser')
    ==> admin:     auto_typed_set('Port', '389')
    ==> admin:     auto_typed_set('CacheTTL', '60')
    ==> admin:     auto_typed_set('SSLEnabled', '1')
    ==> admin:     auto_typed_set('Host', 'ldapserver')
    ==> admin:     auto_typed_set('MaxGroupMembershipSearchLevel', '4')
    ==> admin:
    ==> admin:
    ==> admin:     if control_flag:
    ==> admin:       cmo.setControlFlag(control_flag)
    ==> admin:
    ==> admin:     if attributes:
    ==> admin:       if attributesvalues:
    ==> admin:           properties=String(attributes).split(";")
    ==> admin:           values=String(attributesvalues).split(";")
    ==> admin:
    ==> admin:           numbers  = ['Port','CacheTTL','CacheSize','MaxGroupMembershipSearchLevel']
    ==> admin:           booleans = ['KeepAliveEnabled','UseRetrievedUserNameAsPrincipal','IgnoreDuplicateMembership','DigestReplayDetectionEnabled','UseDefaultUserNameMapper','SSLEnabled']
    ==> admin:           lists =    ['ActiveTypes']
    ==> admin:
    ==> admin:           i = 0
    ==> admin:           for property in properties:
    ==> admin:
    ==> admin:             print "set property " + property + " value "+ values[i]
    ==> admin:             if property in numbers:
    ==> admin:               print "is a int"
    ==> admin:               set(property,int(values[i]))
    ==> admin:
    ==> admin:             elif property in booleans:
    ==> admin:               print "is a boolean"
    ==> admin:               if values[i] == '1' or values[i] == 1:
    ==> admin:                 print "True"
    ==> admin:                 try:
    ==> admin:                   set(property,true)
    ==> admin:                 except:
    ==> admin:                   print "failed to set boolean true, trying string"
    ==> admin:                   try:
    ==> admin:                     set(property, 'true')
    ==> admin:                   except:
    ==> admin:                     raise
    ==> admin:               else:
    ==> admin:                 try:
    ==> admin:                   set(property,false)
    ==> admin:                 except:
    ==> admin:                   print "failed to set boolean false, trying string"
    ==> admin:                   try:
    ==> admin:                     set(property, 'false')
    ==> admin:                   except:
    ==> admin:                     raise
    ==> admin:
    ==> admin:             elif property in lists:
    ==> admin:               print "is a list"
    ==> admin:
    ==> admin:               list_values=String(values[i]).split("::")
    ==> admin:               set(property,jarray.array(list_values, String))
    ==> admin:
    ==> admin:             else:
    ==> admin:               print "is a string"
    ==> admin:               set(property,values[i])
    ==> admin:
    ==> admin:             i = i + 1
    ==> admin:
    ==> admin:     # Authentication Provider Ordering
    ==> admin:     if order:
    ==> admin:         print "setting order"
    ==> admin:
    ==> admin:         cd('/'+path)
    ==> admin:         order_val = int(order)
    ==> admin:         ap = get('AuthenticationProviders')
    ==> admin:         total_aps = len(ap)-1
    ==> admin:         if order_val > total_aps:
    ==> admin:           print "Order value %d exceeds number of authentication providers. Setting to max %d instead." % (order_val, total_aps)
    ==> admin:           order_val = total_aps
    ==> admin:
    ==> admin:         if ap[order_val].getKeyProperty('Name') != realmName.getName()+name:
    ==> admin:             # Find the current index
    ==> admin:             old_index = len(ap)-1
    ==> admin:             if order_val > old_index:
    ==> admin:                 raise Exception("ERROR - Order Value %d is higher than the quantity of Authentication Providers configured. Cannot order." % order_val)
    ==> admin:
    ==> admin:             for provider in ap[::-1]:
    ==> admin:                 if provider.getKeyProperty('Name') == realmName.getName()+name:
    ==> admin:                     print "Ordering %s to position %d" % (name, order_val)
    ==> admin:                     ap.insert(order_val, ap.pop(old_index))
    ==> admin:                     break
    ==> admin:
    ==> admin:                 old_index = old_index - 1
    ==> admin:
    ==> admin:             # Apply the new order
    ==> admin:             set('AuthenticationProviders', ap)
    ==> admin:
    ==> admin:
    ==> admin:     print "done"
    ==> admin:     save()
    ==> admin:     activate()
    ==> admin:     print "~~~~COMMAND SUCCESFULL~~~~"
    ==> admin:
    ==> admin: except:
    ==> admin:     print "Unexpected error:", sys.exc_info()[0]
    ==> admin:     undo('true','y')
    ==> admin:     stopEdit('y')
    ==> admin:     print "~~~~COMMAND FAILED~~~~"
    ==> admin:     raise
    ==> admin: ^^^====================================================================
    ==> admin: Info: Executing wls-script /tmp/wlstScript20160110-5569-148x5z9-0.py with timeout = 120
    ==> admin: Debug: Passing domain default
    ==> admin: Debug: Passing credentials to WLST
    ==> admin: Info: Connecting to wls on url t3://10.10.10.10:7001
    ==> admin: Debug: wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> wls:/Wls1036/serverConfig/SecurityConfiguration/Wls1036/Realms/myrealm> Connecting to t3://10.10.10.10:7001 with userid weblogic ...
    ==> admin:
    ==> admin: Debug: Successfully connected to Admin Server 'AdminServer' that belongs to domain 'Wls1036'.
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: Warning: An insecure protocol was used to connect to the
    ==> admin:
    ==> admin: Debug: server. To ensure on-the-wire security, the SSL port or
    ==> admin:
    ==> admin: Debug: Admin port should be used instead.
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: wls:/Wls1036/serverConfig> Location changed to edit tree. This is a writable tree with
    ==> admin:
    ==> admin: Debug: DomainMBean as the root. To make changes you will need to start
    ==> admin:
    ==> admin: Debug: an edit session via startEdit().
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: For more help, use help(edit)
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: Starting an edit session ...
    ==> admin:
    ==> admin: Debug: Started edit session, please be sure to save and activate your
    ==> admin:
    ==> admin: Debug: changes once you are done.
    ==> admin:
    ==> admin: Debug: com.bea.description : Returns the size of the cache in K.
    ==> admin:
    ==> admin: Debug: com.bea.dynamic : false
    ==> admin:
    ==> admin: Debug: defaultValue : 32
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : CacheSize
    ==> admin:
    ==> admin: Debug: interfaceclassname : int
    ==> admin:
    ==> admin: Debug: minValue : 0
    ==> admin:
    ==> admin: Debug: Name : CacheSize
    ==> admin:
    ==> admin: Debug: Setting generic property CacheSize to 1024
    ==> admin:
    ==> admin: Debug: com.bea.description : Returns the Distinguished Name (DN) of the LDAP user that is used by WebLogic Server to connect to the LDAP server.
    ==> admin:
    ==> admin: Debug: com.bea.dynamic : false
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : Principal
    ==> admin:
    ==> admin: Debug: Name : Principal
    ==> admin:
    ==> admin: Debug: Setting generic property Principal to ldapuser
    ==> admin:
    ==> admin: Debug: com.bea.description : Returns the port number on which the LDAP server is listening.
    ==> admin:
    ==> admin: Debug: com.bea.dynamic : false
    ==> admin:
    ==> admin: Debug: defaultValue : 389
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : Port
    ==> admin:
    ==> admin: Debug: interfaceclassname : int
    ==> admin:
    ==> admin: Debug: maxValue : 65534
    ==> admin:
    ==> admin: Debug: minValue : 1
    ==> admin:
    ==> admin: Debug: Name : Port
    ==> admin:
    ==> admin: Debug: Setting generic property Port to 389
    ==> admin:
    ==> admin: Debug: com.bea.description : Returns the time-to-live (TTL) of the cache in seconds.
    ==> admin:
    ==> admin: Debug: com.bea.dynamic : false
    ==> admin:
    ==> admin: Debug: defaultValue : 60
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : CacheTTL
    ==> admin:
    ==> admin: Debug: interfaceclassname : int
    ==> admin:
    ==> admin: Debug: minValue : 0
    ==> admin:
    ==> admin: Debug: Name : CacheTTL
    ==> admin:
    ==> admin: Debug: Setting generic property CacheTTL to 60
    ==> admin:
    ==> admin: Debug: com.bea.description : Returns whether SSL will be used to connect to the LDAP server.
    ==> admin:
    ==> admin: Debug: com.bea.dynamic : false
    ==> admin:
    ==> admin: Debug: defaultValue : false
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : SSLEnabled
    ==> admin:
    ==> admin: Debug: interfaceclassname : boolean
    ==> admin:
    ==> admin: Debug: Name : SSLEnabled
    ==> admin:
    ==> admin: Debug: Setting boolean property SSLEnabled to 1
    ==> admin:
    ==> admin: Debug: This Exception occurred at Sun Jan 10 16:47:18 CET 2016.
    ==> admin:
    ==> admin: Debug: javax.management.InvalidAttributeValueException: argument type mismatch
    ==> admin:
    ==> admin: Debug: Unexpected error: main.WLSTException
    ==> admin:
    ==> admin: Debug: Discarded all your changes successfully.
    ==> admin:
    ==> admin: Debug: Edit session has been stopped successfully.
    ==> admin:
    ==> admin: Debug: ~~~~COMMAND FAILED~~~~
    ==> admin:
    ==> admin: Error: Could not set 'present' on ensure: command in deamon failed.
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/daemon.rb:65:in `sync'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/utils/wls_daemon.rb:50:in `execute_script'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/utils/wls_access.rb:347:in `execute_wlst'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/utils/wls_access.rb:199:in `wlst'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/utils/wls_access.rb:195:in `each'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/orawls/lib/utils/wls_access.rb:195:in `wlst'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/command_entry.rb:25:in `send'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/command_entry.rb:25:in `execute'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/blank_slate.rb:36:in `execute'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/blank_slate.rb:35:in `each'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/blank_slate.rb:35:in `execute'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/blank_slate.rb:34:in `each'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/blank_slate.rb:34:in `execute'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/script_builder.rb:120:in `execute'
    ==> admin: /tmp/vagrant-puppet/modules-f097dd4f7b47eae2336cb7d4eb41de32/easy_type/lib/easy_type/provider.rb:60:in `create'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/property/ensure.rb:16:in `set_present'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:197:in `send'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:197:in `call_valuemethod'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:498:in `set'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/property.rb:581:in `sync'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:204:in `sync'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:81:in `perform_changes'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:20:in `evaluate'
    ==> admin: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:204:in `apply'

**Comment by hajee** [comment]
It recognises the fact that it is a boolean property:

```
Setting boolean property SSLEnabled to 1
```

On WLS 12 getting a boolean property returns `0`  and `1`. Maybe on 10.3 that is different.  This log doesn't contain an encrypted attribute.

**Comment by biemond** [comment]
this is the first issue.

2nd credential is the same issue as before but you added some try except around it.

**Comment by biemond** [comment]
==> admin: Debug: weblogic.management.NoAccessRuntimeException: Access to sensitive attribute in clear text is not allowed due to the setting of ClearTextCredentialAccessEnabled attribute in SecurityConfigurationMBean. Attr: Credential, MBean name: Security:Name=myrealmActiveDirectoryAuthenticator
==> admin:
==> admin: Debug: Unexpected error: main.WLSTException
==> admin:

**Pull request merged**
