### PR TITLE
Add new 'removeinfectedconnections' property to wls_datasource

### PR DESCRIPTION
**Pull request by alexjfisher**
For consistency accepts '0', '1' as well as true/false.  Property is optional.  If not specified in a manifest, the existing state will not be altered.  See commits for more detailed comments.

### CODE REVIEW

**Comment by alexjfisher** [comment]
@biemond I've done a fair bit of testing, but have been bitten before :)

Perhaps leave it a few days before merging.

**Comment by biemond** [comment]
Thanks a lot 

For wls true or false is internally 1 or 0 so I have to do a lot of translation between the index and the rest. So let's keep it simple.

**Comment by alexjfisher** [comment]
I think letting the type users use true/false would still be good (orawls always seemed a bit odd in this regard), but I could change it my munging false->'0' and true->'1' instead of the other way round.

That would simplify ```to_translate_to_resource``` and the output of puppet resource would remain consistent.  Also, the munging code could probably be refactored into its own class for use by the other properties and types.

Meanwhile, the unit test I added (mainly so the coverage report didn't fail the build :) ), did highlight one possible bug.
https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/wls_datasource.rb#L41
Isn't password a property?

**Comment by biemond** [comment]
basically is it, 

but we do some encrypt/decrypt actions/hacks and in puppet resource we don't show you the real password.  So that's why it is still a property.

**Pull request merged**
