### PR TITLE
Change defaulttargetting behavior for jms components

### PR DESCRIPTION
**Pull request by BasLangenberg**
Hi Edwin,

I noticed that the wls_jms_topic and wls_jms_queue types did not interpreted the defaulttargetting parameters for the both. I also made a small change to wls_jms_connection_factory.

The logic goes in favorite of defaulttargetting if both defaulttargetting and subdeployment are set, because the first is the exception in our environment on the latter. I don't know if this is a common use case, so this might need some refactoring. I don't know what your experiences are on this topic.

Cheers!
Bas

### CODE REVIEW

**Comment by biemond** [comment]
Hi Bas,

I mostly use default targetting of the jms module for Connnecties factories and sub deployment for topics/ queues because they should be target-ed 1 or more jms servers.

So I don't combine them on a queue or topic.

I see that the default for defaulttargetting = 1, So it will always do default target-ting even with a subdeployment defined.

But in this PR when you set defaulttargetting = 0 and don't use a subdeployment it still enables it. 

So let's add both as separate WLST statements (sub and default targetting )  and add some business rules.
let's check in all the WLST if defaulttargetting = 1 and subdeployment is not empty and subdeployment is not empty plus defaulttargetting = 0 else raise a WLST exception. 

This exception will be picked up by puppet and the user need to handle this.

Cheers

**Comment by BasLangenberg** [comment]
Hi Edwin,

Thanks for your feedback.

I have made some additional changes. The WLST scripts should now follow more business rules.

I learned today that when I push a repo to Github which is in a pull request, the pr gets updated automatically. I'm not done testing yet. ;-) I will take this into account in the future.

Cheers!
Bas

**Comment by biemond** [comment]
Nice, looks great

I will merge it and test it myself.

Thanks

**Comment by BasLangenberg** [comment]
Thanks!

I have some problems getting the exception throwing to work correctly in Puppet. Not sure how to approach this. Still a newbie, maybe.

I'll have another look on Wednesday...

**Comment by BasLangenberg** [comment]
Hi Edwin,

As promised. There was an issue with the tests I did making me go down the wrong road, but it is working as expected now.

Can you please review the current state of the PR? 

Let me know what you think.

Cheers!
- Bas

**Pull request merged**
