### PR TITLE
Utils.py to be generated for each domain when creating multiple domains in an puppet run

### PR DESCRIPTION
**Pull request by yadavnikhil**
When running puppet to create multiple domains in single puppet run, due to condition: if !defined(File['utils.py']), it would be created just for one domain & second domain creation fails as this file is not found for others.

Modified as below (unique for each domain & will run once for each domain_name passed):

if !defined(File["utils.py_${domain_name}"]) {
      file { "utils.py_${domain_name}":

### CODE REVIEW

**Comment by biemond** [comment]
thanks but there should only be utils.py on each node because it doesn't contain any spefic domain data

So why do you get this error. Are you using a different download folder for every domain if so we probably only have to change the title of the utils file type to full path

**Comment by yadavnikhil** [comment]
I'm passing download_dir unique for each domain as the user accounts are different & I didnt wanted to merge files for different domains. Also, as I have fixed the download_dir variable in hiera, i'm using same for copydomain & packdomain for multi-machine setup with same path for all purpose for particular domain. 

Btw the solution of having single utils.py also works for me provided I keep download_dir same for all domains I create.

**Comment by biemond** [comment]
I think when we do this 

it will work in all situations

    # the utils.py used by the wlst
    if !defined(File["${download_dir}/utils.py"]) {
      file { '"${download_dir}/utils.py":
        ensure  => present,
        content => template('orawls/domains/utils.py.erb'),
        replace => true,
        backup  => false,
        mode    => '0775',
        owner   => $os_user,
        group   => $os_group,
        require => File[$download_dir],
      }
    }

**Comment by yadavnikhil** [comment]
Yes, absolutely this should work fine.
Thanks.

**Pull request closed without merging**
