### PR TITLE
Fix typo in cross domain

### PR DESCRIPTION
**Pull request by hajee**

### CODE REVIEW

**Comment by biemond** [comment]
Really,  I changed the utils script so it follows python code check. Camelcase looks really strange now

**Comment by hajee** [comment]
Ok. So I will change the call then.

**Comment by hajee** [comment]
What syntax would you like? I still see only CamelCase in https://github.com/biemond/biemond-orawls/blob/master/templates/domains/utils.py.erb

**Comment by biemond** [comment]
Strange 15 days ago in commit dc7cc7a I change all domains py scripts and also published it 
Maybe it is in the wrong branch

**Comment by hajee** [comment]
Problem is caused by commit 9266779149a07b148b6f74ed4f8c7ad411d22574. The changes all code back. Must be gone wrong during mergen. I would expect git to pickup such a merge comflict. I think best solution right now is to rollback that PR. I will then make a new PR on the fixed master.

**Comment by biemond** [comment]
I did the rollback so everything should be ok again.

**Comment by matonb** [comment]
Seems to be working for me now that commit has been rolled back :)

**Pull request closed without merging**
