### PR TITLE
Nir1218 patch 1

### PR DESCRIPTION
**Pull request by nir1218**
Add the option to enable or disable CDI Implicit Bean Discovery for Weblogic 12.2

### CODE REVIEW

**Comment by nir1218** [comment]
Hi,
Any idea what's the issue?
Thanks
Nir

**Comment by biemond** [comment]
Thanks , looks good . let me check this PR.

**Comment by nir1218** [comment]
Hi,
please advise if this is something you would like to merge.
Thank you.

**Comment by biemond** [comment]
Hi, no problem. I just forget to do this. :)

**Comment by nir1218** [comment]
Hi,
Can we expedite this request please?
I have two pull requests, this one and 504, that are essentials to our framework.
Thank you much.

**Pull request merged**
