### PR TITLE
Fix functions to also run on WebLogic 10.3

### PR DESCRIPTION
**Pull request by hajee**
Edwin,

Can you try this? This should fix your problems at WebLogic 10.3

### CODE REVIEW

**Comment by biemond** [comment]
It works on wls 10.3 but it fails on 12.2.1 encryption attribute ( second run by retrieving auth provider properties )

      'ActiveDirectoryAuthenticator':
        ensure:             'present'
        control_flag:       'SUFFICIENT'
        providerclassname:  'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator'
        provider_specific:
          'Credential':                     'password'
          'GroupBaseDN':                    'DC=ad,DC=company,DC=org'
          'GroupFromNameFilter':            '(&(sAMAccountName=%g)(objectclass=group))'
          'GroupMembershipSearching':       'limited'
          'Host':                           'ad.company.org'
          'MaxGroupMembershipSearchLevel':  4
          'Principal':                      'CN=SER_WASadmin,OU=Service Accounts,DC=ad,DC=company,DC=org'
          'UserBaseDN':                     'DC=ad,DC=company,DC=org'
          'UserFromNameFilter':             '(&(sAMAccountName=%u)(objectclass=user))'
          'UserNameAttribute':              'sAMAccountName'
          'Port':                           389
          'CacheTTL':                       60
          'CacheSize':                      1024
          'ConnectTimeout':                 2
          'ConnectionRetryLimit':           2



    ==> admin: Debug: wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> Connecting to t3s://10.10.10.10:7002 with userid weblogic ...
    ==> admin:
    ==> admin: Debug: Successfully connected to Admin Server "AdminServer" that belongs to domain "Wls1221".
    ==> admin:
    ==> admin: Debug:
    ==> admin:
    ==> admin: Debug: wls:/Wls1221/serverConfig/> SecurityConfiguration/Wls1221/Realms/myrealm/AuthenticationProviders/ActiveDirectoryAuthenticator
    ==> admin:
    ==> admin: Debug: Credential
    ==> admin:
    ==> admin: Debug: description : The credential (generally a password) used to authenticate the LDAP user                  that is defined in the Principal attribute.
    ==> admin:
    ==> admin: Debug: dynamic : true
    ==> admin:
    ==> admin: Debug: encrypted : true
    ==> admin:
    ==> admin: Debug: descriptorType : Attribute
    ==> admin:
    ==> admin: Debug: displayName : Credential
    ==> admin:
    ==> admin: Debug: Name : Credential
    ==> admin:
    ==> admin: Debug: attribute SecurityConfiguration/Wls1221/Realms/myrealm/AuthenticationProviders/ActiveDirectoryAuthenticator/Credential is encrypted.
    ==> admin:
    ==> admin: Debug: ~~~~COMMAND SUCCESFULL~~~~
    ==> admin:
    ==> admin: Info: Skip WLST for domain plain
    ==> admin: Info: Executing: wlstScript with action execute
    ==> admin: Prepare to run: /tmp/wlstScript20160112-21251-pprp3v.py,oracle,default,/opt/oracle/middleware12c/wlserver,weblogic,weblogic1,t3s://10.10.10.10:7002
    ==> admin: vvv===================================================================
    ==> admin: real_domain='default'
    ==> admin:
    ==> admin: try:
    ==> admin:     puppet = open("/tmp/wlstScript.out", "w")
    ==> admin:     print >>puppet, 'value'
    ==> admin:
    ==> admin:     ##
    ==> admin:     # This function gets the password at the specified key and decrypts it. The specfied key must point
    ==> admin:     # to a key in the tree that contains the encrypted password.
    ==> admin:     #
    ==> admin:     key                       = 'SecurityConfiguration/Wls1221/Realms/myrealm/AuthenticationProviders/ActiveDirectoryAuthenticator/CredentialEncrypted'
    ==> admin:     encrypted_password        = get(key)
    ==> admin:     encrypted_password_string = password_to_string(encrypted_password)
    ==> admin:     value                     = decrypt_value(encrypted_password_string)
    ==> admin:
    ==> admin:
    ==> admin:     print >>puppet, value
    ==> admin:     puppet.close()
    ==> admin:     print "~~~~COMMAND SUCCESFULL~~~~"
    ==> admin:
    ==> admin: except:
    ==> admin:     print "Unexpected error:", sys.exc_info()[0]
    ==> admin:     print "~~~~COMMAND FAILED~~~~"
    ==> admin:     raise
    ==> admin: ^^^====================================================================
    ==> admin: Info: Executing wls-script /tmp/wlstScript20160112-21251-pprp3v.py with timeout = 120

**Comment by biemond** [comment]
the error 

==> admin: Debug: wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> wls:/Wls1221/serverConfig/> Connecting to t3s://10.10.10.10:7002 with userid weblogic ...
==> admin:
==> admin: Debug: Successfully connected to Admin Server "AdminServer" that belongs to domain "Wls1221".
==> admin:
==> admin: Debug:
==> admin:
==> admin: Debug: wls:/Wls1221/serverConfig/> Unexpected error: exceptions.AttributeError
==> admin:
==> admin: Debug: ~~~~COMMAND FAILED~~~~


wls:/Wls1221/serverConfig/SecurityConfiguration/Wls1221/Realms/myrealm/AuthenticationProviders/ActiveDirectoryAuthenticator> ls()
dr--   Realm

-r--   AllGroupsFilter                              null
-r--   AllUsersFilter                               null
-r--   BindAnonymouslyOnReferrals                   false
-r--   CacheEnabled                                 true
-r--   CacheSize                                    1024
-r--   CacheTTL                                     60
-r--   ConnectTimeout                               2
-r--   ConnectionPoolSize                           6
-r--   ConnectionRetryLimit                         2
-r--   ControlFlag                                  SUFFICIENT
-r--   Credential                                   ******
-r--   CredentialEncrypted                          ******

**Comment by biemond** [comment]
it looks like it crashes on this, very strange because manual it works with wlst.sh

I will look at wls_settings to set the post classpath.

print 'begin'
cd('/')
key                       = '<%= value %>'
encrypted_password        = get(key)
print '1'
encrypted_password_string = password_to_string(encrypted_password)
print '2'
value                     = decrypt_value(encrypted_password_string)
print 'end'


def decrypt_value(encrypted_value):
    print '10'
    cd('/')
    domain_dir = get('RootDirectory')
    print '11'
    domain_dir_path = os.path.abspath(domain_dir)
    print '12'
    encrypt_srv = weblogic.security.internal.SerializedSystemIni.getEncryptionService(domain_dir_path)
    print '13'


==> admin: Debug: Successfully connected to Admin Server "AdminServer" that belongs to domain "Wls1221".
==> admin:
==> admin: Debug:
==> admin:
==> admin: Debug: wls:/Wls1221/serverConfig/> begin
==> admin:
==> admin: Debug: 1
==> admin:
==> admin: Debug: 2
==> admin:
==> admin: Debug: 10
==> admin:
==> admin: Debug: 11
==> admin:
==> admin: Debug: 12
==> admin:
==> admin: Debug: Unexpected error: exceptions.AttributeError
==> admin:
==> admin: Debug: ~~~~COMMAND FAILED~~~~

**Comment by biemond** [comment]
I give up for now. 

I tried everything by setting these parameters and the -DORACLE_HOME parameters just like wlst.sh

/usr/java/jdk1.8.0_65/lib/tools.jar:/opt/oracle/middleware12c/wlserver/modules/features/wlst.wls.classpath.jar
-Xverify:none -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader 
-DORACLE_HOME='/opt/oracle/middleware12c/oracle_common'

**Comment by hajee** [comment]
I checked you puppet definition on 12.1. There it works as well. I'll also have a look later.

**Pull request merged**
