### PR TITLE
Added frontendhost httpport & httpsport to wls_server. Slightly changed

### PR DESCRIPTION
**Pull request by robh007**
Ability to set FRONTENDHOST, HTTPPORT & HTTPSPORT within wls_server - taken from wls_cluster type. I'm not convinced that's idempotent though, so I've changed to allow removal of frontendhost. With the wls_cluster implmentation it looked like you could set a host but never remove it.

Change-Id: I30ea09de5f8deb17d1609c16c4e680e47e4deafe

### CODE REVIEW

**Comment by biemond** [comment]
Thanks a lot,

Do you know if one of  the http port,  https port or fronten_host attributes are optional and is 0 the default  for the http or https fronted port.

if so we can add 0 as default to the http and https port puppet attribute. This way we can also remove it from the modify  plus maybe add its own if statement in WLST to  all the attributes ( even when 0 is the default)

Cheers

**Comment by robh007** [comment]
Morning Edwin,

I've updated to include defaults for each of the types. I've therefore removed the if statements from the WLST code, as all attributes are either valid defaults or specified data values. This way removal and adding of the attributes works as expected.

**Comment by biemond** [comment]
Nice :+1: 

did you commit these changes in your branch

**Comment by biemond** [comment]
I already see the new changes 

thanks

**Pull request merged**
