### PR TITLE
Fix wls authentication provider

### PR DESCRIPTION
**Pull request by hajee**
Edwin,

Can you check this one out? What I've done is:

1. add an t`try` `except` block on fetching values. When a value cannot be fetched, it will continue with an empty value
2. I deduct the way to set the attribute, based on the type of the currrent value. This should allow setting all variables

If 2 works consistently, we could extract this into a method and use this everywhere. I think this would make a lot of settings much easier. 

Let me know what you think about it.

### CODE REVIEW

**Comment by biemond** [comment]
Ok,

2 questions, 

- How you will make sure that credentials won't lead to change with every puppet run.
- How will you handle booleans because for to set a value I need to use True or False and for retrieving I will get '0' or '1' and this is not integer. Maybe we allow 1 or 0 as same value for True or False. 

but better approach is to add type to the provider_specific hash, like '1' Boolean or '5' int , 'credentials' password and default will be a string value.
This will make our code clean and can also handle new sec provider attributes

**Comment by hajee** [comment]
>How you will make sure that credentials won't lead to change with every puppet run.

Good question ;-). At this point in time you can't. Maybe we need the `attributes` and `attributesvalues` back. I'm working on the password issue now. Maybe this would help in the future.

>How will you handle booleans because for to set a value I need to use True or False and for retrieving I will get '0' or '1' and this is not integer. Maybe we allow 1 or 0 as same value for True or False.

People need to specify a 0 or a 1 when they want to set a boolean value like `SSLEnabled`. true or false won't work.I have looked at the AD provider in your example and checked out the several boolean values in there. They all  accept a nummeric value. That's why I didn't add a type for Booleans. If we need to, I can add a Boolean in the `elif` block.

>but better approach is to add type to the provider_specific hash, like '1' Boolean or '5' int , 'credentials' password and default will be a string value. This will make our code clean and can also handle new sec provider attributes

But it is also very noisy in the definition. WebLogic already knows (most of its) type information. Maybe we can make this optional somehow. So you can define it only when you really need it to be different than the deducted type.

**Comment by biemond** [comment]
nice

let's see if we can fix the credentials issue. I think the attribute is mostly called credential and this is a parameter and not a property.

**Comment by hajee** [comment]
I'am going to close this one and wait for #292 to be merged. I have a new version that used a lot of the functions added in that PR.

**Pull request closed without merging**
