### PR TITLE
[WLS_DOMAIN] Add property exalogicoptimizationsenabled

### PR DESCRIPTION
**Pull request by hajee**

### CODE REVIEW

**Comment by biemond** [comment]
Nice,

I see these are double in the modify script 

      if setconfigbackupenabled:
        cmo.setConfigBackupEnabled(formatBoolean(setconfigbackupenabled))

      if setconfigbackupenabled:
        cmo.setConfigBackupEnabled(formatBoolean(setconfigbackupenabled))

and this one is gone 

     if setconfigurationaudittype:
       cmo.setConfigurationAuditType(setconfigurationaudittype)

also don't know if this property also is available on 10.3.6 or before maybe add a try except

      exalogicoptimizationsenabled = str(get('ExalogicOptimizationsEnabled'))

**Comment by hajee** [comment]
I have checked on a 10.3.6. installation and the attribute `ExalogicOptimizationsEnabled` does exists. So no need to protect it with a try except. I have also fixed the other cut/paste error.

**Comment by biemond** [comment]
Ok, so you don't use weblogic 10.3.2 anymore at your customer

**Comment by hajee** [comment]
No. Not 10.3.2

**Pull request merged**
