### PR TITLE
Look Mom... No More Hiera

### PR DESCRIPTION
**Pull request by bryanjbelanger**
Removed hiera. It is best handled in a profile.

Also, leveraging class variables. Remove parameters from manifests where redundant.

Less code, less maintenance.

Will likely break the examples though...

### CODE REVIEW

**Comment by biemond** [comment]
Thanks a lot for this big PR 👍 

For now I will use this because this is always the same but I don't know if this will works all puppet 3 versions
 

```
 +  $middleware_home_dir  = $::orawls::weblogic::middleware_home_dir
 +  $weblogic_home_dir    = $::orawls::weblogic::weblogic_home_dir
 +  $wls_domains_dir      = $::orawls::weblogic::wls_domains_dir
 +  $wls_apps_dir         = $::orawls::weblogic::wls_apps_dir
 +  $jdk_home_dir         = $::orawls::weblogic::jdk_home_dir
 +  $os_user              = $::orawls::weblogic::os_user
 +  $os_group             = $::orawls::weblogic::os_group
 +  $download_dir         = $::orawls::weblogic::download_dir
 +  $oracle_base_home_dir = $::orawls::weblogic::oracle_base_home_dir
 +  $source               = $::orawls::weblogic::source
 +  $temp_directory       = $::orawls::weblogic::temp_directory
```

**Comment by standagh** [comment]
Hi

Removing redundant properties/parameters is good. No questions about it.

But removing properties from class/type definitions breaks compatibility.

If goal is to remove hiera parameters why parameters are moved outside "headers"? Why not use (for example for opatch):
```
define orawls::opatch(
  $ensure                  = 'present',  #present|absent
  $oraInst_path            = undef,
  $oracle_product_home_dir = undef, # /opt/oracle/middleware11gR1
  $patch_id                = undef,
  $patch_file              = undef,
  $remote_file             = true,  # true|false
  $middleware_home_dir     = $::orawls::weblogic::middleware_home_dir
  $weblogic_home_dir       = $::orawls::weblogic::weblogic_home_dir
  $wls_domains_dir         = $::orawls::weblogic::wls_domains_dir
  ...
)
```
In this situation it would be removed hiera dependency and compatibility is not broken.

My motive here is that we have requirement to install multiple instances of WLS on single host. 
Unfortunately `weblogic.pp` is single manifest file (except `urandomfix.pp`) that is class and not type. I solved it by redefining wbelogic class to be type. See pull request 327 I just sent - `weblogic_type.pp`. The changes to `weblogic.pp` are minimal.

If parameters are removed from type definitions I think it would not be possible to use weblogic as type and hance multiple instances of WLS on a host.

If there is a requirement to set common values in single place I would propose to create manifest file `manifests/params.pp` where all common parameters for most situations will be defined:
```
$middleware_home_dir
$weblogic_home_dir
...
```

And in types parameters will be used as:
```
define orawls::opatch(
  $ensure                  = 'present',  #present|absent
  $oraInst_path            = undef,
  $oracle_product_home_dir = undef, # /opt/oracle/middleware11gR1
  $patch_id                = undef,
  $patch_file              = undef,
  $remote_file             = true,  # true|false
  $middleware_home_dir     = $::orawls::params::middleware_home_dir
  $weblogic_home_dir       = $::orawls::params::weblogic_home_dir
  $wls_domains_dir         = $::orawls::params::wls_domains_dir
  ...
)
```
But please don't break compatibility :)

**Comment by standagh** [comment]
Hi (again)

It seems that there are parameters in manifests type definitions that are never used in the manifest. In this situation I understand they may be removed from type definition but IMHO there is no point in redefining them as variables that are not used. I briefly checked opatch.pp and control.pp and found following parameters that are not used:

```
manifests/opatch.pp:
- $middleware_home_dir
- $weblogic_home_dir
- $wls_domains_dir
- $wls_apps_dir
- $log_output
- $oracle_base_home_dir
```

```
manifests/control.pp
- $version
- $wls_apps_dir
- $download_dir
- $log_output
- $oracle_base_home_dir
- $source
- $temp_directory
```

**Comment by bryanjbelanger** [comment]
Yes. This is not backward compatible. If that is the requirement, and it makes sense, it needs to be moved into params. I will take another swipe. Reject the pull.

I didn’t see the weblogic_type.pp. I guess if there is a business need for multiple instances this is required.

Thanks,

Bryan Belanger | Principal Consultant

Azcender: www.azcender.com<http://www.azcender.com/>

phone: +1 (248) 613-1538 | email: bbelanger@azcender.com<mailto:bryan@belangerconsulting.com>

On Apr 13, 2016, at 6:20 AM, Standa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Removing redundant properties/parameters is good. No questions about it.

But removing properties from class/type definitions breaks compatibility.

If goal is to remove hiera parameters why parameters are moved outside "headers"? Why not use (for example for opatch):

define orawls::opatch(
  $ensure                  = 'present',  #present|absent
  $oraInst_path            = undef,
  $oracle_product_home_dir = undef, # /opt/oracle/middleware11gR1
  $patch_id                = undef,
  $patch_file              = undef,
  $remote_file             = true,  # true|false
  $middleware_home_dir     = $::orawls::weblogic::middleware_home_dir
  $weblogic_home_dir       = $::orawls::weblogic::weblogic_home_dir
  $wls_domains_dir         = $::orawls::weblogic::wls_domains_dir
  ...
)


In this situation it would be removed hiera dependency and compatibility is not broken.

My motive here is that we have requirement to install multiple instances of WLS on single host.
Unfortunately weblogic.pp is single manifest file (except urandomfix.pp) that is class and not type. I solved it by redefining wbelogic class to be type. See pull request 327 I just sent - weblogic_type.pp. The changes to weblogic.pp are minimal.

If parameters are removed from type definitions I think it would not be possible to use weblogic as type and hance multiple instances of WLS on a host.

If there is a requirement to set common values in single place I would propose to create manifest file manifests/params.pp where all common parameters for most situations will be defined:

$middleware_home_dir
$weblogic_home_dir
...


And in types parameters will be used as:

define orawls::opatch(
  $ensure                  = 'present',  #present|absent
  $oraInst_path            = undef,
  $oracle_product_home_dir = undef, # /opt/oracle/middleware11gR1
  $patch_id                = undef,
  $patch_file              = undef,
  $remote_file             = true,  # true|false
  $middleware_home_dir     = $::orawls::params::middleware_home_dir
  $weblogic_home_dir       = $::orawls::params::weblogic_home_dir
  $wls_domains_dir         = $::orawls::params::wls_domains_dir
  ...
)


But please don't break compatibility :)

**Comment by bryanjbelanger** [comment]
Noted. Will remove on next attempt.

Thanks,

Bryan Belanger | Principal Consultant

Azcender: www.azcender.com<http://www.azcender.com/>

phone: +1 (248) 613-1538 | email: bbelanger@azcender.com<mailto:bryan@belangerconsulting.com>

On Apr 13, 2016, at 6:28 AM, Standa <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi (again)

It seems that there are parameters in manifests type definitions that are never used in the manifest. In this situation I understand they may be removed from type definition but IMHO there is no point in redefining them as variables that are not used. I briefly checked opatch.pp and control.pp and found following parameters that are not used:

manifests/opatch.pp:
- $middleware_home_dir
- $weblogic_home_dir
- $wls_domains_dir
- $wls_apps_dir
- $log_output
- $oracle_base_home_dir


manifests/control.pp
- $version
- $wls_apps_dir
- $download_dir
- $log_output
- $oracle_base_home_dir
- $source
- $temp_directory

**Comment by bryanjbelanger** [comment]
Rework per Biedmond comments.

**Pull request closed without merging**
