### PR TITLE
RFC: Optionally install OWSM when creating a weblogic 10.3.6 OSB domain

### PR DESCRIPTION
**Pull request by alexjfisher**
I need to do a bit more testing, but this is what I'm proposing so far...

### CODE REVIEW

**Comment by alexjfisher** [comment]
@biemond  Sorry it's been over 3 weeks...

No issues discovered yet with the OSB servers I've built using this branch.  So good to merge I think.
Let me know if you'd like me to rebase first.

Thanks,
Alex

**Comment by biemond** [comment]
nice, I was thinking about the impact of this 

if this only is for 11g then we need to add an extra wls 1036 or 1111 check. I think it goes wrong with owsm enabled and version 1213 which is a also valid option.

**Comment by alexjfisher** [comment]
Like this? https://github.com/biemond/biemond-orawls/commit/02501793c8f8e7e2313bfe40c321aa396f556b1d

**Comment by biemond** [comment]
perfect

**Pull request merged**
