### PR TITLE
Nodemanager depends on extensions for properties file in 12.1.2 and 12.1.3

### PR DESCRIPTION
**Pull request by rlhatcher**
Hi Edwin

This fixes the problem I was having with the non-default nodemanager port and SOA template

Thanks,
Ron

### CODE REVIEW

**Comment by biemond** [comment]
Cool,

but domain extensions are optional, let's see if we can make a conditional require on extend domain  in the nodemanager step or conditional before on nodemanager in the extend domain step.

**Comment by rlhatcher** [comment]
Indeed - I thought of that after I submitted this. As you say, it's fine for SOA but I'll have a think and see if I can work out a nice clean way to get the dependancy correct.

**Comment by biemond** [comment]
nice, but why did you close this PR

**Comment by rlhatcher** [comment]
Hi there - just submitted a better one ...

**Pull request closed without merging**
