### PR TITLE
Multiple NULL characters written to the csv file wlst<<Domain>.out at the beginning to the new record

### PR DESCRIPTION
**Pull request by amtpar**
Multiple NULL characters written to the csv file wlst<<Domain>.out at the beginning to the new record.
In this fix we remove all the null characters that appears in the wlst<<Domain>.out file if exist.

This change solve the following exception that was thrown by convert_csv_data_to_hash:
**Failed to apply catalog: Illegal quoting in line 3**

### CODE REVIEW

**Comment by biemond** [comment]
thanks

**Comment by amtpar** [comment]
Thanks biemond :)
when do you think the next release will be ready?
Thanks,
Amit

**Comment by amtpar** [comment]
What is the planning of releasing 2.0.19?

**Comment by amtpar** [comment]
What is the release planning of version 2.0.19?

Thanks:)

**Comment by biemond** [comment]
I will test it myself and publish it tonight

thanks

**Comment by amtpar** [comment]
Thanks a lot 👍

**Pull request merged**
