### PR TITLE
Add credential to domain creation

### PR DESCRIPTION
**Pull request by hajee**

### CODE REVIEW

**Comment by biemond** [comment]
let's rename this parameter to domain_credential , set_domain_credential or change_domain_credential  this gives it some more context.

**Comment by hajee** [comment]
It is on the `orawls::domain`. Isn't it a bit double? Isn't it better to write some good documentation instead?

**Comment by biemond** [comment]
not really because with credential you think first about the weblogic password and this changes the domain password (most people don't know there is a domain password ) plus it looks like you can set it instead it is just a flag to do this or not.

**Comment by hajee** [comment]
Done

**Comment by biemond** [comment]
your code won't work because I already overrule it later in the domain py script code with the weblogic password.

https://github.com/biemond/biemond-orawls/blob/0d8ef02d047eb4908626e481f957625d8a437249/templates/domains/domain.py.erb#L100

So for now I will disable the code and look at it

**Comment by hajee** [comment]
Is the domainPassword really the same as the credential? That is very confusing

**Comment by biemond** [comment]
You can check the utils script which contains all the general wlst methods and it does the same as your code

**Pull request merged**
