### PR TITLE
Added support for webcenter sites 12.2.1.2

### PR DESCRIPTION
**Pull request by bFekete**
Only WCS will use the new domain_1221.py.epp for now. Added an extension as suggested.

### CODE REVIEW

**Comment by biemond** [comment]
thanks, perfect, exactly how I like it & dummy proof.

what is your fmw puppet install config then I can try it out in a test vagrant box.

**Comment by biemond** [comment]
can you also fix the lint errors https://travis-ci.org/biemond/biemond-orawls/jobs/245910329

```
$ bundle exec rake lint
manifests/domain.pp - ERROR: trailing whitespace found on line 156
manifests/domain.pp - ERROR: trailing whitespace found on line 290
manifests/domain.pp - ERROR: trailing whitespace found on line 366
manifests/domain.pp - ERROR: trailing whitespace found on line 376
manifests/utils/rcu.pp - ERROR: trailing whitespace found on line 76

```

**Comment by bFekete** [comment]
My work laptop can't run vagrant which is depressing. My testing environment is completely different. Here's a modified yaml.

```
---
# Global variables in Node Scope
wls_jdk_home_dir:        &wls_jdk_home_dir        '/opt/java'
wls_weblogic_log_output: &wls_weblogic_log_output true
wls_machine_ip:          &wls_machine_ip          '10.100.10.10'
wls_machine_hostname:    &wls_machine_hostname    'admin.example.com'

oracle_base_home_dir: &oracle_base_home_dir '/opt/oracle'
apps_dir:             &apps_dir             '/opt/oracle/config/applications'
domains_dir:          &domains_dir          '/opt/oracle/config/domains'
download_dir:         &download_dir         '/opt/oracle/installers'
wls_log_dir:          &wls_log_dir          '/opt/log/weblogic/nodemanager'
os_user:              &os_user              'oracle'
os_group:             &os_group             'oracleadmns'

# WCS
wls_weblogic_user_wcs:       &wls_weblogic_user_wcs       'wcs12c'
wls_weblogic_password_wcs:   &wls_weblogic_password_wcs   'wcsadmin'
wls_middleware_home_dir_wcs: &wls_middleware_home_dir_wcs '/opt/oracle/products/wcs'
wls_weblogic_home_dir_wcs:   &wls_weblogic_home_dir_wcs '/opt/oracle/products/wcs/wlserver'

# Installs WebLogic Fusion Middleware Infrastructure
weblogic_instances:
  'fmw_infra':
    version:                   12212
    filename:                  'fmw_12.2.1.2.0_infrastructure.jar'
    fmw_infra:                 true
    puppet_download_mnt_point: '/mnt/Weblogicfiles/wls_12212_Linux'
    middleware_home_dir:       *wls_middleware_home_dir_wcs
    weblogic_home_dir:         *wls_weblogic_home_dir_wcs
    jdk_home_dir:              *wls_jdk_home_dir
    log_output:                *wls_weblogic_log_output

##
# Installs WebLogic Fusion Middleware WebCenters Sites
# Possible wcs_modes are: sites, examples, satellite. Defaults at sites.
##
fmw_installations:
  'wcs12.2.1.2':
    version:                   12212
    fmw_product:               'wcs'
    fmw_file1:                 'fmw_12.2.1.2.0_wcsites_Disk1_1of1.zip'
    wcs_mode:                  'sites'
    puppet_download_mnt_point: '/mnt/Weblogicfiles/wls_12212_Linux'
    middleware_home_dir:       *wls_middleware_home_dir_wcs
    weblogic_home_dir:         *wls_weblogic_home_dir_wcs
    jdk_home_dir:              *wls_jdk_home_dir
    log_output:                *wls_weblogic_log_output
    oracle_base_home_dir:      *oracle_base_home_dir
    download_dir:              *download_dir
    os_user:                   *os_user
    os_group:                  *os_group

# Creates Domain and initial configuration
domain_instances:
  'wcs':
    version:                               12212
    domain_name:                           'wcs'
    domain_template:                       'wcs'
    middleware_home_dir:                   *wls_middleware_home_dir_wcs
    weblogic_home_dir:                     *wls_weblogic_home_dir_wcs
    jdk_home_dir:                          *wls_jdk_home_dir
    log_output:                            *wls_weblogic_log_output
    weblogic_user:                         *wls_weblogic_user_wcs
    weblogic_password:                     *wls_weblogic_password_wcs
    nodemanager_username:                  *wls_weblogic_user_wcs
    nodemanager_password:                  *wls_weblogic_password_wcs
    domain_password:                       *wls_weblogic_password_wcs
    adminserver_address:                   &wls_machine_hostname
    adminserver_machine_name:              &wls_machine_hostname
    adminserver_port:                      7001
    adminserver_listen_on_all_interfaces:  true
    nodemanager_port:                      5556
    nodemanager_secure_listener:           true
    repository_database_url :             'jdbc:oracle:thin:@//10.100.10.11:1521/SITES_DEV.example.com'
    rcu_database_url:                     '10.100.10.11:1521/SITES_DEV.example.com'
    repository_prefix:                    'DEV'
    repository_sys_user:                  'sys'
    repository_sys_password:              'cbr900RR'
    repository_password:                  'wcsadmin#1'
    wcs_satellite:                         false
    create_default_coherence_cluster:      false # The template its basing the domain off of already provides it. Keep FALSE
    download_dir:              *download_dir
    os_user:                   *os_user
    os_group:                  *os_group
    wls_domains_dir:           *domains_dir
    wls_apps_dir:              *apps_dir
	
    
# Configures the NodeManager and starts up it
nodemanager_instances:
  'nodemanager_wcs':
    version:                     12212
    domain_name:                 'wcs'
    ohs_standalone:              true
    middleware_home_dir:         *wls_middleware_home_dir_wcs
    weblogic_home_dir:           *wls_weblogic_home_dir_wcs
    jdk_home_dir:                *wls_jdk_home_dir
    log_output:                  *wls_weblogic_log_output
    log_file:                    'nodemanager_wcs.log'
    nodemanager_address:         &wls_machine_ip
    nodemanager_port:            5556
    nodemanager_secure_listener: true
    properties:
      'log_level': 'SEVERE'
    download_dir:              *download_dir
    os_user:                   *os_user
    os_group:                  *os_group
    wls_domains_dir:           *domains_dir
    log_dir:                   *wls_log_dir

```

**Comment by biemond** [comment]
I see when I do wcs_satellite = true some deployment has failed as status.
also maybe handy to set a machine on the servers.

**Comment by bFekete** [comment]
It might be because I didn't add some logic around create_default_coherence_cluster: true. I'll have to test it.

I was just using wls_server to assign the machines to the servers but that could be added too.

**Comment by biemond** [comment]
ok,

I fixed create_default_coherence_cluster on your 12.2.1 domain template but that didn't work. I need to look at the real cause in the logs.

no problem, I guess we can assign it to local machine.

**Comment by bFekete** [comment]
I tested it on your vagrant setup with wcs_satellite=true and it worked. I could access the console from http://10.10.10.21:7001/console.

**Pull request merged**
