### PR TITLE
No more hiera V2

### PR DESCRIPTION
**Pull request by bryanjbelanger**
Moved class instance variables into parameter sections. No adding or removing of parameters.

Kiera still gone.

### CODE REVIEW

**Comment by biemond** [comment]
Hi,

So you are now doing forms. 

I think I will move this to a branch and combine it with the internal data which comes with puppet 4.3.
this way people get early access to the changes plus with internal hiera data we can make it more cleaner.

Thanks

**Comment by bryanjbelanger** [comment]
HI Biemond,

I am developing into master. That was a no-no.

Your solution makes sense. Can we still do the no hiera version. I will branch my frame work and revert if you will merge on that.

Hiera in the module is killing us.

Thanks,

On May 4, 2016, at 8:39 AM, Edwin Biemond <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

So you are now doing forms.

I think I will move this to a branch and combine it with the internal data which comes with puppet 4.3.
this way people get early access to the changes plus with internal hiera data we can make it more cleaner.

Thanks

**Comment by biemond** [comment]
the no hiera will still work, but with internal data I can cleanup the centos, redhat6,7, solaris parameters, 
see this http://www.craigdunn.org/2016/04/designing-modules-in-a-puppet-4-world/  the data section

pretty cool

**Comment by biemond** [comment]
So I started the work on puppet 4 with epp, datatypes, facts, internal module data and using params to remove the all the hiera lookup.

check the puppet 4 branch

**Comment by bryanjbelanger** [comment]
Thank you Biemond!



On Feb 5, 2017, at 8:40 AM, Edwin Biemond <notifications@github.com<mailto:notifications@github.com>> wrote:


So I started the work on puppet 4 with epp, datatypes, facts, internal module data and using params to remove the all the hiera lookup.

check the puppet 4 branch

**Pull request closed without merging**
