### PR TITLE
Type enhancements + option for file based security store

### PR DESCRIPTION
**Pull request by bradmcnaughton**
Hey Edwin, here's some enhancements.

* wls_datasource include xaproperties
* identity asserter type added for customising defaultidentityasserter
* better error handling for auth provider ordering
* optional retain file based security store in fmwcluster.pp
* readme updates to explain all the above

Cheers,
Brad

### CODE REVIEW

**Comment by biemond** [comment]
Nice, very appreciated

**Comment by biemond** [comment]
Hi Brad, 

Did you also changed files/providers/wls_datasource/index.py.erb for retrieving the xa properties of a datasource

**Comment by bradmcnaughton** [comment]
Hi Edwin,

No I didn't add xaproperties to the indexing, although it can be done
reasonably easily, I think. I'm not sure if puppet will detect a false
change if a default xa property is not explicitly specified in the
hiera/manifest. I'll try this out next week and see if it can be done.

**Comment by biemond** [comment]
ok perfect, else we should change xaproperties to a param and not a property.

**Comment by biemond** [comment]
maybe it is easier to have separate xa properties there are not that many.

**Pull request merged**
